---
build_from:
  aarch64: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20-arm64v8
  amd64: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20-amd64
  armv7: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20-arm32v7
  i386: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io