version: 0.0.14
slug: "ha-zigbee-bridge"
name: "Zigbee bridge"
description: "Addon для создания виртуальных Zigbee устройств для возможности взаимодействия с HA через другие zigbee шлюзы"
url: https://github.com/devlabpro/ha-zigbee-bridge
codenotary: avperschin@gmail.com
advanced: true
arch:
  - aarch64
  - amd64
  - armv7
  - i386
hassio_api: true
hassio_role: default
homeassistant_api: true
ingress: true
init: false
map:
  - addon_config:rw
  - share
options:
  ZB_ESP_DEVICE_PORT: ""
panel_icon: mdi:zigbee
panel_title: Zigbee bridge
ports:
  8099/tcp: null
schema:
  ZB_ESP_DEVICE_PORT: "str?"
startup: services
timeout: 30
uart: true